apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-logzio
  labels:
    tier: monitoring
    app: fluentd-logzio
    version: v1
spec:
  template:
    metadata:
      labels:
        name: fluentd-logzio
    spec:
      hostPID: true
      hostIPC: true
      hostNetwork: true
      containers:
      - resources:
          requests:
            cpu: 0.15
        securityContext:
          privileged: true
        env:
        - name: LOG_PATH
          value: "/var/log/containers/*.log"
        - name: LOGZIO_URL
          value: __YOUR_LOGZ_URL_
        - name: LOGZIO_TOKEN
          value: __YOUR_LOGZ_TOKEN_
        - name: LOGZIO_TYPE
          value: __YOUR_LOGZ_TYPE_
        image: logzloggingk8s/daemonset-fluentd-logz
        name: fluentd-logzio
        volumeMounts:
        - name: varlog
          mountPath: "/var/log"
        - name: varlibdockercontainers
          mountPath: "/var/lib/docker/containers"
      volumes:
      - name: varlog
        hostPath:
          path: "/var/log"
      - name: varlibdockercontainers
        hostPath:
          path: "/var/lib/docker/containers"
          readOnly: true

